name: Deploy Clock App

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # test kubernetes    
      - name: Test cluster connection
        run: kubectl get nodes
 
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
           clean: true

      # Step 2a: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t clock-app .
          echo "Build Done"
      # Step 2b: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag clock-app ${{ secrets.DOCKERHUB_USERNAME }}/clock-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/clock-app:latest


      # Step 3: Run Docker container
      - name: Run Docker container
        run: |
          docker run -d -p 8081:80 --name clock clock-app

      # Step 4: Verify site
      - name: Verify site
        run: |
          sleep 5
          curl -s http://localhost:8081 || exit 1

      # Step 5: Rollback if failed
      - name: Rollback if failed
        if: failure()
        run: |
          docker stop clock || true
          docker run -d -p 8081:80 clock-app:previous || true
